apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: web
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
  annotations:
    collectord.io/prometheus.1-port: '7788'
    collectord.io/prometheus.1-path: '/metrics'
spec:
  replicas: 2
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: 10.0.2.2:5000/employeedb-web
        name: web
        ports:
        - containerPort: 3000
          name: http-server
        - containerPort: 7788
          name: metrics